### ISSUE TITLE
ie无法使用

### ISSUE THREAD

**Issue by Benleie** [Grewer/downloadByUrl#1]
IE11下，并没有开始下载
`document.frames["saveFileFrame"].document.execCommand('saveAs')`貌似没有执行

**Comment by Benleie** [comment]
点击之后无事发生

**Comment by Grewer** [comment]
@Benleie console 有报什么错吗

**Comment by Grewer** [comment]
@Benleie 试下 demo 里的能正常下载吗 https://grewer.github.io/downloadByUrl/example/
